---

- firewalld: service=https permanent=true state=enabled

- firewalld: service=http permanent=true state=enabled

- firewalld: service=mosh permanent=true state=enabled

- name: create extrassh service
  copy: src=extrassh.xml dest=/etc/firewalld/services/extrassh.xml
  register: extrassh_xml

- name: reload firewalld rules
  command: firewall-cmd --reload
  when: extrassh_xml|changed

- firewalld: service=extrassh permanent=true state=enabled
